### ISSUE TITLE
框选判断碰撞检测逻辑BUG

### ISSUE THREAD

**Issue by Chanyon** [F-star/suika#106]
如果有n-1个矩形被框选，第n个矩形没被全部选中时，也会选中。
![image](https://github.com/F-star/suika/assets/40350332/f1eb8c13-24a8-4738-834a-d2a7d7ede287)

**Comment by F-star** [comment]
选中模式是可以配置的，在 setting 类的 selectionMode 属性，默认为 intersect（相交），不需要完全框选中，部分相交即可选中。

如果你希望是完全包围的关系，可以将其设置为 contain。

**Comment by Chanyon** [comment]
Thank you!
