### ISSUE TITLE
钢笔绘制线条闭合区域计算不对

### ISSUE THREAD

**Issue by zyronon** [F-star/suika#156]
这是你的
![image](https://github.com/F-star/suika/assets/19986642/e93e90e6-3f21-4bc7-947c-02c7b9aca45e)

下面是figma的
![image](https://github.com/F-star/suika/assets/19986642/fc2c72fe-ac4e-446a-a221-09d78598088e)

**Comment by F-star** [comment]
figma 的钢笔工具创建的图形是它**自创的矢量网格**（vector network）。

感兴趣的话可以看看这两篇文章：
- https://madebyevan.com/figma/introducing-vector-networks/
- https://alexharri.medium.com/the-engineering-behind-figmas-vector-networks-688568e37110

suika 编辑器使用的 **传统意义上的路径**，效果是和 svg 和 canvas 2d 的 path 一样，上面的图 1 就是 svg 和 canvas 2d 的效果（非零环绕数填充）。

figma 用的是自己定义的填充算法（计算轮廓多边形作为填充区域），所以得到图 2 的效果。关于计算多边形轮廓，我有实现一个简化的算法，感兴趣可以看看：

https://github.com/F-star/polygon-alg

figma 的矢量网格比较复杂，细节非常多，因为个人精力有限，目前 suika 编辑器是不支持的。

后期可能会考虑~
