### ISSUE TITLE
垂直标尺文字有点被挤压了

### ISSUE THREAD

**Issue by pansong291** [F-star/suika#169]
说一个小问题，垂直标尺上绘制的数字有一点被挤压了，对比一下水平的 `700` 和 垂直的 `700` 就能发现，还是有一点明显的，我是 Windows 系统 Edge 浏览器。我目前还没发现有什么比较简单又好的解决办法。

**Comment by F-star** [comment]
不同操作系统的文字渲染可能有一些区别，也可能是用的字体不一样。你可以考虑指定一下字体，或者用 Bitmap Text

**Comment by pansong291** [comment]
![PixPin-20240717-112934](https://github.com/user-attachments/assets/48fd7fc2-1555-4d14-b766-f62019243a9c)
看上图，垂直的 `600` 和 水平的 `600` 比起来，有点被挤压了。

**Comment by F-star** [comment]
那应该是这个设备的 canvas 2d 的 bug，旋转 90 绘制会有问题，先关闭了。还是前面说的，解决方法是用 bitmap，分成一个个字符的纹理拼起来，不要再用 canvas 的 drawText。或者换个字体试试

![image](https://github.com/user-attachments/assets/60bf09ba-70ba-438b-a8ae-3e2c864d1ba9)
