### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [F-star/suika#99]
你好，我们这里是蓝桥云课，偶然关注到您的仓库，我们对您分享的这个项目很感兴趣，我们平台提供了基于 linux 的线上免费实操环境，想邀请您结合我们的环境和您的项目，制作一门实战课程学习这一技术，课程上线后相信会为您带来不错的收益分成，若您有兴趣尝试的话，可以直接添加我们的官方合作微信：shiyanloukecheng 了解合作详情，期待您的联系～

**Comment by F-star** [comment]
目前没有出付费课程的打算
